# Generated by Django 3.2.6 on 2022-05-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('authentication', '0002_auto_20220521_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fav_cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cuisine'),
        ),
    ]
